name: "Issue / PR Triage"

on:
  issues:
    types: ["labeled"]
  schedule:
    # Run pull request triage once an hour. Ideally, this would be on
    # "labeled" types of pull request events, but that doesn't work if the pull
    # request is from another fork. For example, see
    # https://github.com/actions/labeler/issues/12
    - cron: '42 * * * *'

concurrency:
  group: issue-triage
  cancel-in-progress: true

jobs:
  triage:
    if: github.repository == 'bytecodealliance/wasmtime'
    runs-on: ubuntu-latest
    steps:

    # Automatically label PRs that touch certain directories with certain
    # labels.
    - uses: bytecodealliance/labeler@f6157f32fa13c4d01e14d3df38d4b6e17e36eb5f # schedule-fork
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

    # @-mention people who are subscribed to a label when an issue/PR is given
    # that label.
    - uses: bytecodealliance/subscribe-to-label-action@f669a502948c4667f8db07a79e9c5c87b7852e0b # v1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

    # Leave pre-determined comments on issues/PRs that are given a certain label.
    - uses: bytecodealliance/label-messager-action@2f83571c7af396405ff3bad7777b187b9dd60f88 # v1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
